framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    session: true
    handle_all_throwables: true
    router:
        utf8: true
    validation:
        email_validation_mode: html5
    asset_mapper:
        paths:
            - assets/
    rate_limiter:
        voucher_check:
            policy: fixed_window
            limit: 20
            interval: '15 minutes'
