twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        portal_name: '%portal.name%'
        portal_city: '%portal.city%'
        portal_contact_email: '%portal.contact_email%'
        portal_timezone: '%portal.timezone%'
