<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Generated by Doctrine from the PR1 user mapping.
 */
final class Version20261005115034 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the portal user table with unique email and authentication fields.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE portal_user (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, firstName VARCHAR(100) NOT NULL, lastName VARCHAR(100) NOT NULL, active TINYINT NOT NULL, createdAt DATETIME NOT NULL, updatedAt DATETIME NOT NULL, UNIQUE INDEX UNIQ_76511E4E7927C74 (email), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE portal_user');
    }
}
