<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Generated by Doctrine for the PR2 company directory and master data.
 */
final class Version20261005135423 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add companies, categories, images, opening hours and contact persons.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE Category (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(180) NOT NULL, slug VARCHAR(180) NOT NULL, description LONGTEXT DEFAULT NULL, icon VARCHAR(80) DEFAULT NULL, position INT NOT NULL, active TINYINT NOT NULL, createdAt DATETIME NOT NULL, updatedAt DATETIME NOT NULL, UNIQUE INDEX UNIQ_FF3A7B97989D9B62 (slug), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE Company (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(180) NOT NULL, slug VARCHAR(180) NOT NULL, shortDescription VARCHAR(500) DEFAULT NULL, description LONGTEXT DEFAULT NULL, active TINYINT NOT NULL, featured TINYINT NOT NULL, street VARCHAR(180) DEFAULT NULL, houseNumber VARCHAR(30) DEFAULT NULL, postalCode VARCHAR(20) DEFAULT NULL, city VARCHAR(180) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, website VARCHAR(2048) DEFAULT NULL, facebookUrl VARCHAR(2048) DEFAULT NULL, instagramUrl VARCHAR(2048) DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, createdAt DATETIME NOT NULL, updatedAt DATETIME NOT NULL, UNIQUE INDEX UNIQ_800230D3989D9B62 (slug), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE company_category (company_id INT NOT NULL, category_id INT NOT NULL, INDEX IDX_1EDB0CAC979B1AD6 (company_id), INDEX IDX_1EDB0CAC12469DE2 (category_id), PRIMARY KEY (company_id, category_id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE CompanyImage (id INT AUTO_INCREMENT NOT NULL, fileName VARCHAR(100) NOT NULL, altText VARCHAR(255) NOT NULL, title VARCHAR(180) DEFAULT NULL, position INT NOT NULL, type VARCHAR(20) NOT NULL, createdAt DATETIME NOT NULL, company_id INT NOT NULL, INDEX IDX_2859A56979B1AD6 (company_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE ContactPerson (id INT AUTO_INCREMENT NOT NULL, firstName VARCHAR(100) NOT NULL, lastName VARCHAR(100) NOT NULL, position VARCHAR(180) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, mobile VARCHAR(50) DEFAULT NULL, primaryContact TINYINT NOT NULL, sortOrder INT NOT NULL, active TINYINT NOT NULL, company_id INT NOT NULL, image_id INT DEFAULT NULL, INDEX IDX_271C6326979B1AD6 (company_id), INDEX IDX_271C63263DA5256D (image_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE OpeningHour (id INT AUTO_INCREMENT NOT NULL, dayOfWeek SMALLINT NOT NULL, opensAt TIME DEFAULT NULL, closesAt TIME DEFAULT NULL, closed TINYINT NOT NULL, position INT NOT NULL, company_id INT NOT NULL, INDEX IDX_FD410212979B1AD6 (company_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('ALTER TABLE company_category ADD CONSTRAINT FK_1EDB0CAC979B1AD6 FOREIGN KEY (company_id) REFERENCES Company (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE company_category ADD CONSTRAINT FK_1EDB0CAC12469DE2 FOREIGN KEY (category_id) REFERENCES Category (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE CompanyImage ADD CONSTRAINT FK_2859A56979B1AD6 FOREIGN KEY (company_id) REFERENCES Company (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ContactPerson ADD CONSTRAINT FK_271C6326979B1AD6 FOREIGN KEY (company_id) REFERENCES Company (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ContactPerson ADD CONSTRAINT FK_271C63263DA5256D FOREIGN KEY (image_id) REFERENCES CompanyImage (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE OpeningHour ADD CONSTRAINT FK_FD410212979B1AD6 FOREIGN KEY (company_id) REFERENCES Company (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE company_category DROP FOREIGN KEY FK_1EDB0CAC979B1AD6');
        $this->addSql('ALTER TABLE company_category DROP FOREIGN KEY FK_1EDB0CAC12469DE2');
        $this->addSql('ALTER TABLE CompanyImage DROP FOREIGN KEY FK_2859A56979B1AD6');
        $this->addSql('ALTER TABLE ContactPerson DROP FOREIGN KEY FK_271C6326979B1AD6');
        $this->addSql('ALTER TABLE ContactPerson DROP FOREIGN KEY FK_271C63263DA5256D');
        $this->addSql('ALTER TABLE OpeningHour DROP FOREIGN KEY FK_FD410212979B1AD6');
        $this->addSql('DROP TABLE Category');
        $this->addSql('DROP TABLE Company');
        $this->addSql('DROP TABLE company_category');
        $this->addSql('DROP TABLE CompanyImage');
        $this->addSql('DROP TABLE ContactPerson');
        $this->addSql('DROP TABLE OpeningHour');
    }
}
