parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude: '../src/{Entity,Doctrine,Geo/GeoPoint.php,Geo/GeocodingResult.php,Geo/DirectoryLocation.php,Kernel.php}'

    App\Geo\GeocodingServiceInterface: '@App\Geo\NominatimGeocodingService'
